[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
colored = "3.0.0"
lazy_static = "1.5.0"
paste = "1.0.15"

[build-dependencies]
indoc = "2.0.6"
